#define VK_NO_PROTOTYPES
#include <windows.h>
#include <memory>
#include "shaders/dlssnr/DlssNr_Vk.h"
#include "D24VkTracking.h"
namespace A=DlssNr::VkAudit;
#include <vulkan/vulkan.h>
#include <cstdio>
#include <vector>
#include <cstring>
#include <cmath>
#include <nvsdk_ngx_vk.h>
#include "../dx11_probe_parameters.h"
#define FUN(name) auto name=reinterpret_cast<PFN_##name>(GetProcAddress(vk,#name));if(!name)return 90;
#define OK(call) {VkResult r=(call);printf("%s=%d\n",#call,int(r));fflush(stdout);if(r!=VK_SUCCESS)return 1;}
int main(int argc,char**){bool pure=argc>1;
 auto vk=LoadLibraryExW(L"vulkan-1.dll",nullptr,LOAD_LIBRARY_SEARCH_SYSTEM32);if(!vk)return 2;
 FUN(vkGetDeviceProcAddr);FUN(vkCreateInstance);FUN(vkEnumeratePhysicalDevices);FUN(vkGetPhysicalDeviceProperties);FUN(vkGetPhysicalDeviceQueueFamilyProperties);FUN(vkEnumerateDeviceExtensionProperties);FUN(vkGetPhysicalDeviceFeatures2);FUN(vkCreateDevice);FUN(vkGetDeviceQueue);FUN(vkCreateCommandPool);FUN(vkAllocateCommandBuffers);FUN(vkBeginCommandBuffer);FUN(vkEndCommandBuffer);FUN(vkQueueSubmit);FUN(vkCreateFence);FUN(vkWaitForFences);FUN(vkDestroyFence);FUN(vkDestroyCommandPool);FUN(vkDestroyDevice);FUN(vkDestroyInstance);
 VkApplicationInfo app{VK_STRUCTURE_TYPE_APPLICATION_INFO};app.pApplicationName="D24 Vulkan host";app.apiVersion=VK_API_VERSION_1_2;VkInstanceCreateInfo ic{VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO};ic.pApplicationInfo=&app;VkInstance instance{};OK(vkCreateInstance(&ic,nullptr,&instance));
 uint32_t n=0;OK(vkEnumeratePhysicalDevices(instance,&n,nullptr));std::vector<VkPhysicalDevice> devices(n);OK(vkEnumeratePhysicalDevices(instance,&n,devices.data()));VkPhysicalDevice pd{};for(auto d:devices){VkPhysicalDeviceProperties p{};vkGetPhysicalDeviceProperties(d,&p);printf("device=%s vendor=%x\n",p.deviceName,p.vendorID);if(p.vendorID==0x10de)pd=d;}if(!pd)return 3;
 OK(vkEnumerateDeviceExtensionProperties(pd,nullptr,&n,nullptr));std::vector<VkExtensionProperties> ext(n);OK(vkEnumerateDeviceExtensionProperties(pd,nullptr,&n,ext.data()));
 const char* wanted[]={"VK_NVX_binary_import","VK_NVX_image_view_handle","VK_KHR_push_descriptor","VK_EXT_buffer_device_address"};for(auto name:wanted){bool found=false;for(auto& e:ext)if(!strcmp(e.extensionName,name))found=true;printf("extension=%s supported=%d\n",name,found);if(!found)return 4;}
 vkGetPhysicalDeviceQueueFamilyProperties(pd,&n,nullptr);std::vector<VkQueueFamilyProperties> q(n);vkGetPhysicalDeviceQueueFamilyProperties(pd,&n,q.data());uint32_t family=~0u;for(uint32_t i=0;i<n;i++)if((q[i].queueFlags&(VK_QUEUE_GRAPHICS_BIT|VK_QUEUE_COMPUTE_BIT))==(VK_QUEUE_GRAPHICS_BIT|VK_QUEUE_COMPUTE_BIT)){family=i;break;}if(family==~0u)return 5;
 VkPhysicalDeviceBufferDeviceAddressFeaturesEXT v12{VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_BUFFER_DEVICE_ADDRESS_FEATURES_EXT};VkPhysicalDeviceFeatures2 supported{VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FEATURES_2};supported.pNext=&v12;vkGetPhysicalDeviceFeatures2(pd,&supported);if(!v12.bufferDeviceAddress)return 6;
 VkPhysicalDeviceBufferDeviceAddressFeaturesEXT enabled{VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_BUFFER_DEVICE_ADDRESS_FEATURES_EXT};enabled.bufferDeviceAddress=VK_TRUE;VkPhysicalDeviceFeatures base{};base.shaderInt64=VK_FALSE;base.shaderStorageImageExtendedFormats=VK_TRUE;float priority=1;VkDeviceQueueCreateInfo qc{VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO};qc.queueFamilyIndex=family;qc.queueCount=1;qc.pQueuePriorities=&priority;VkDeviceCreateInfo dc{VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO};dc.pNext=&enabled;dc.pEnabledFeatures=&base;dc.queueCreateInfoCount=1;dc.pQueueCreateInfos=&qc;dc.enabledExtensionCount=4;dc.ppEnabledExtensionNames=wanted;VkDevice device{};OK(vkCreateDevice(pd,&dc,nullptr,&device));VkQueue queue{};vkGetDeviceQueue(device,family,0,&queue);
 auto nr=LoadLibraryExW(L"E:\\DLSSNR\\builds\\D24_Vulkan\\nvngx_dlssnr.dll",nullptr,LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR|LOAD_LIBRARY_SEARCH_SYSTEM32);if(!nr)return 7;
 auto init=(int(*)(unsigned long long,const wchar_t*,VkInstance,VkPhysicalDevice,VkDevice,int,const void*))GetProcAddress(nr,"NVSDK_NGX_VULKAN_Init_Ext");auto create=(int(*)(VkCommandBuffer,int,const void*,void**))GetProcAddress(nr,"NVSDK_NGX_VULKAN_CreateFeature");auto release=(int(*)(void*))GetProcAddress(nr,"NVSDK_NGX_VULKAN_ReleaseFeature");if(!init||!create||!release)return 8;
 volatile int code=init(0,L"E:\\DLSSNR\\builds\\D24_Vulkan",instance,pd,device,0x15,nullptr);printf("ngx_init=%08x\n",int(code));fflush(stdout);if(code!=1)return 9;
 VkCommandPoolCreateInfo pc{VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO};pc.queueFamilyIndex=family;pc.flags=VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;VkCommandPool pool{};OK(vkCreateCommandPool(device,&pc,nullptr,&pool));VkCommandBufferAllocateInfo ac{VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO};ac.commandPool=pool;ac.level=VK_COMMAND_BUFFER_LEVEL_PRIMARY;ac.commandBufferCount=1;VkCommandBuffer cmd{};OK(vkAllocateCommandBuffers(device,&ac,&cmd));VkCommandBufferBeginInfo bc{VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};OK(vkBeginCommandBuffer(cmd,&bc));

 VkCommandPool pools[4]{pool}; VkCommandBuffer cmds[4]{cmd}; VkFence fences[4]{};
 VkFenceCreateInfo extraFenceInfo{VK_STRUCTURE_TYPE_FENCE_CREATE_INFO};
 for(unsigned slot=0;slot<4;slot++){
   OK(vkCreateFence(device,&extraFenceInfo,nullptr,&fences[slot]));
   if(slot){OK(vkCreateCommandPool(device,&pc,nullptr,&pools[slot]));ac.commandPool=pools[slot];OK(vkAllocateCommandBuffers(device,&ac,&cmds[slot]));}
 }
 A::RegisterDevice(device,vkGetDeviceProcAddr);for(unsigned slot=0;slot<4;slot++)A::Allocate(device,pools[slot],family,1,&cmds[slot]);
 // No recorded references survive a resize: complete submissions, then reset every pool.
 for(unsigned cycle=0;cycle<3;cycle++){
 unsigned width=cycle==1?512:256, height=cycle==2?512:256;
 auto pass=std::make_unique<DlssNr_Vk>("host",device,pd);if(!pass->IsInit())return 32;
 printf("cycle=%u width=%u height=%u inflight=4\n",cycle,width,height);
 if(cycle){cmd=cmds[0];OK(vkBeginCommandBuffer(cmd,&bc));}
 ProbeParameters p;p.Set("Width",width);p.Set("Height",height);p.Set("DLSSNR.Width",width);p.Set("DLSSNR.Height",height);p.Set("DLSSNR.Hint.Render.Preset",1u);p.Set("DLSSNR.ScalingRatio",1.0f);p.Set("DLSSNR.Intensity",1.0f);p.Set("DLSSNR.Enabled",1u);void* handle=nullptr;code=create(cmd,18,&p,&handle);printf("ngx_create=%08x handle=%p\n",int(code),handle);fflush(stdout);if(code!=1)return 10;
 OK(vkEndCommandBuffer(cmd));VkFenceCreateInfo fc{VK_STRUCTURE_TYPE_FENCE_CREATE_INFO};VkFence fence{};OK(vkCreateFence(device,&fc,nullptr,&fence));VkSubmitInfo si{VK_STRUCTURE_TYPE_SUBMIT_INFO};si.commandBufferCount=1;si.pCommandBuffers=&cmd;OK(vkQueueSubmit(queue,1,&si,fence));OK(vkWaitForFences(device,1,&fence,VK_TRUE,10000000000ull)); FUN(vkCreateImage);FUN(vkGetImageMemoryRequirements);FUN(vkGetPhysicalDeviceMemoryProperties);FUN(vkAllocateMemory);FUN(vkBindImageMemory);FUN(vkCreateImageView);FUN(vkCreateBuffer);FUN(vkGetBufferMemoryRequirements);FUN(vkBindBufferMemory);FUN(vkCmdPipelineBarrier);FUN(vkCmdClearColorImage);FUN(vkCmdCopyImageToBuffer);FUN(vkResetCommandPool);FUN(vkResetFences);FUN(vkMapMemory);FUN(vkUnmapMemory);FUN(vkDestroyImageView);FUN(vkDestroyImage);FUN(vkDestroyBuffer);FUN(vkFreeMemory);
 VkPhysicalDeviceMemoryProperties mp{};vkGetPhysicalDeviceMemoryProperties(pd,&mp);auto memoryType=[&](unsigned mask,VkMemoryPropertyFlags flags){for(unsigned i=0;i<mp.memoryTypeCount;i++)if((mask&(1u<<i))&&(mp.memoryTypes[i].propertyFlags&flags)==flags)return i;throw 1;};
 VkImage images[6]{};VkDeviceMemory memories[6]{};VkImageView views[6]{};NVSDK_NGX_Resource_VK resources[6]{};VkFormat formats[]={VK_FORMAT_R32G32B32A32_SFLOAT,VK_FORMAT_R32_SFLOAT,VK_FORMAT_R16G16_SFLOAT,VK_FORMAT_R16G16B16A16_SFLOAT,VK_FORMAT_R16G16B16A16_SFLOAT,VK_FORMAT_R32G32B32A32_SFLOAT};VkImageSubresourceRange range{VK_IMAGE_ASPECT_COLOR_BIT,0,1,0,1};
 for(unsigned i=0;i<6;i++){VkImageCreateInfo info{VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO};info.imageType=VK_IMAGE_TYPE_2D;info.format=formats[i];info.extent={width,height,1};info.mipLevels=1;info.arrayLayers=1;info.samples=VK_SAMPLE_COUNT_1_BIT;info.tiling=VK_IMAGE_TILING_OPTIMAL;info.usage=VK_IMAGE_USAGE_SAMPLED_BIT|VK_IMAGE_USAGE_STORAGE_BIT|VK_IMAGE_USAGE_TRANSFER_SRC_BIT|VK_IMAGE_USAGE_TRANSFER_DST_BIT;OK(vkCreateImage(device,&info,nullptr,&images[i]));VkMemoryRequirements req{};vkGetImageMemoryRequirements(device,images[i],&req);VkMemoryAllocateInfo ma{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};ma.allocationSize=req.size;ma.memoryTypeIndex=memoryType(req.memoryTypeBits,VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);OK(vkAllocateMemory(device,&ma,nullptr,&memories[i]));OK(vkBindImageMemory(device,images[i],memories[i],0));VkImageViewCreateInfo vi{VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO};vi.image=images[i];vi.viewType=VK_IMAGE_VIEW_TYPE_2D;vi.format=formats[i];vi.subresourceRange=range;OK(vkCreateImageView(device,&vi,nullptr,&views[i]));resources[i].Type=NVSDK_NGX_RESOURCE_VK_TYPE_VK_IMAGEVIEW;resources[i].ReadWrite=true;resources[i].Resource.ImageViewInfo={views[i],images[i],range,formats[i],width,height};}
 VkBuffer buffer{};VkDeviceMemory bufferMemory{};VkBufferCreateInfo bi{VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO};bi.size=uint64_t(width)*height*16*4;bi.usage=VK_BUFFER_USAGE_TRANSFER_DST_BIT;OK(vkCreateBuffer(device,&bi,nullptr,&buffer));VkMemoryRequirements br{};vkGetBufferMemoryRequirements(device,buffer,&br);VkMemoryAllocateInfo ba{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};ba.allocationSize=br.size;ba.memoryTypeIndex=memoryType(br.memoryTypeBits,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);OK(vkAllocateMemory(device,&ba,nullptr,&bufferMemory));OK(vkBindBufferMemory(device,buffer,bufferMemory,0));
 const char* roles[]={"Color","Depth","MVec","Output"};for(unsigned i=0;i<4;i++){std::string prefix="DLSSNR.";prefix+=roles[i];p.Set(prefix.c_str(),static_cast<void*>(&resources[i]));p.Set((prefix+"SubrectBaseX").c_str(),0u);p.Set((prefix+"SubrectBaseY").c_str(),0u);p.Set((prefix+"SubrectWidth").c_str(),width);p.Set((prefix+"SubrectHeight").c_str(),height);}p.Set("DLSSNR.MVecScaleX",1.0f);p.Set("DLSSNR.MVecScaleY",1.0f);p.Set("DLSSNR.DepthInverted",0u);p.Set("DLSSNR.UseAutoMask",0u);
 auto evaluate=(int(*)(VkCommandBuffer,const void*,const void*,void*))GetProcAddress(nr,"NVSDK_NGX_VULKAN_EvaluateFeature");if(!evaluate)return 12;
 std::vector<float> reference;double means[2]{};unsigned bad=0;
 for(unsigned frame=0;frame<60;frame++){
 cmd=cmds[frame%4];OK(vkResetCommandPool(device,pools[frame%4],0));OK(vkResetFences(device,1,&fences[frame%4]));OK(vkBeginCommandBuffer(cmd,&bc));A::Invalidate(cmd);
 for(unsigned i=0;i<6;i++){VkImageMemoryBarrier barrier{VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER};barrier.srcAccessMask=frame?VK_ACCESS_MEMORY_READ_BIT|VK_ACCESS_MEMORY_WRITE_BIT:0;barrier.dstAccessMask=VK_ACCESS_TRANSFER_WRITE_BIT;barrier.oldLayout=frame?(i>=3?VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL:VK_IMAGE_LAYOUT_GENERAL):VK_IMAGE_LAYOUT_UNDEFINED;barrier.newLayout=VK_IMAGE_LAYOUT_GENERAL;barrier.srcQueueFamilyIndex=barrier.dstQueueFamilyIndex=VK_QUEUE_FAMILY_IGNORED;barrier.image=images[i];barrier.subresourceRange=range;vkCmdPipelineBarrier(cmd,VK_PIPELINE_STAGE_ALL_COMMANDS_BIT,VK_PIPELINE_STAGE_TRANSFER_BIT,0,0,nullptr,0,nullptr,1,&barrier);VkClearColorValue clear{};if(i==0){clear.float32[0]=frame%20<10?0.15f:0.3f;clear.float32[1]=0.2f;clear.float32[2]=0.25f;clear.float32[3]=1;}if(i==1)clear.float32[0]=0.5f;if(i==3)for(auto& v:clear.float32)v=777.0f;vkCmdClearColorImage(cmd,images[i],VK_IMAGE_LAYOUT_GENERAL,&clear,1,&range);}
 VkMemoryBarrier mb{VK_STRUCTURE_TYPE_MEMORY_BARRIER};mb.srcAccessMask=VK_ACCESS_MEMORY_WRITE_BIT;mb.dstAccessMask=VK_ACCESS_MEMORY_READ_BIT|VK_ACCESS_MEMORY_WRITE_BIT;vkCmdPipelineBarrier(cmd,VK_PIPELINE_STAGE_ALL_COMMANDS_BIT,VK_PIPELINE_STAGE_ALL_COMMANDS_BIT,0,1,&mb,0,nullptr,0,nullptr);
 
 auto transition=[&](unsigned i,VkImageLayout from,VkImageLayout to){VkImageMemoryBarrier b{VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER};b.srcAccessMask=VK_ACCESS_MEMORY_READ_BIT|VK_ACCESS_MEMORY_WRITE_BIT;b.dstAccessMask=b.srcAccessMask;b.oldLayout=from;b.newLayout=to;b.srcQueueFamilyIndex=b.dstQueueFamilyIndex=VK_QUEUE_FAMILY_IGNORED;b.image=images[i];b.subresourceRange=range;vkCmdPipelineBarrier(cmd,VK_PIPELINE_STAGE_ALL_COMMANDS_BIT,VK_PIPELINE_STAGE_ALL_COMMANDS_BIT,0,0,nullptr,0,nullptr,1,&b);};
 DlssNrConstants constants{};constants.Mode=DlssNrMode_Encode;constants.Width=width;constants.Height=height;constants.GuideWidth=width;constants.GuideHeight=height;constants.WhitePoint=1;constants.TransferStrength=1;constants.ColourStrength=1;constants.MaxRatio=4;
 transition(0,VK_IMAGE_LAYOUT_GENERAL,VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL);
 if(!pass->Dispatch(cmd,constants,width,height,views[0],{}, {}, {},views[4],views[5],formats[4],formats[5]))return 33;
 A::Handoff(cmd,nullptr,nullptr,0);p.Set("DLSSNR.Color",static_cast<void*>(&resources[4]));p.Set("DLSSNR.Reset",frame%10==0?1u:0u);code=pure?1:evaluate(cmd,handle,&p,nullptr);printf("frame=%u evaluate=%08x\n",frame,int(code));fflush(stdout);if(code!=1)return 13;
 vkCmdPipelineBarrier(cmd,VK_PIPELINE_STAGE_ALL_COMMANDS_BIT,VK_PIPELINE_STAGE_ALL_COMMANDS_BIT,0,1,&mb,0,nullptr,0,nullptr);VkBufferImageCopy copy{};copy.imageSubresource={VK_IMAGE_ASPECT_COLOR_BIT,0,0,1};copy.imageExtent={width,height,1};copy.bufferOffset=uint64_t(frame%4)*width*height*16;
 transition(3,VK_IMAGE_LAYOUT_GENERAL,VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL);
 transition(4,VK_IMAGE_LAYOUT_GENERAL,VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL);
 transition(5,VK_IMAGE_LAYOUT_GENERAL,VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL);
 transition(0,VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,VK_IMAGE_LAYOUT_GENERAL);
 constants.Mode=DlssNrMode_Resolve;if(pure)constants.TransferStrength=0;
 if(!pass->Dispatch(cmd,constants,width,height,views[4],pure?views[4]:views[3],views[5],{},views[0],{},formats[0],VK_FORMAT_R16G16B16A16_SFLOAT))return 34;
 vkCmdCopyImageToBuffer(cmd,images[0],VK_IMAGE_LAYOUT_GENERAL,buffer,1,&copy);mb.dstAccessMask=VK_ACCESS_HOST_READ_BIT;vkCmdPipelineBarrier(cmd,VK_PIPELINE_STAGE_ALL_COMMANDS_BIT,VK_PIPELINE_STAGE_HOST_BIT,0,1,&mb,0,nullptr,0,nullptr);OK(vkEndCommandBuffer(cmd));auto batch=A::Prepare(A::Commands(1,&si));OK(vkQueueSubmit(queue,1,&si,fences[frame%4]));A::Submitted(queue,batch,VK_SUCCESS,[&](VkFence f){return vkQueueSubmit(queue,0,nullptr,f);});if(frame%4==3){OK(vkWaitForFences(device,4,fences,VK_TRUE,10000000000ull));for(unsigned readFrame=frame-3;readFrame<=frame;readFrame++){void* data=nullptr;OK(vkMapMemory(device,bufferMemory,0,VK_WHOLE_SIZE,0,&data));auto pixels=static_cast<float*>(data)+uint64_t(readFrame%4)*width*height*4;double sum=0;for(unsigned i=0;i<width*height*4;i++){if(!std::isfinite(pixels[i])||pixels[i]==777)bad++;if(i%4==0)sum+=pixels[i];}if(readFrame==0)reference.assign(pixels,pixels+width*height*4);if(readFrame==20||readFrame==40)if(memcmp(reference.data(),pixels,uint64_t(width)*height*16))bad++;if(readFrame==0)means[0]=sum/(width*height);if(readFrame==10)means[1]=sum/(width*height);vkUnmapMemory(device,bufferMemory);}}}
 printf("pixel_bad=%u input_response=%f reset_replay_checked=3\n",bad,means[1]-means[0]);if(bad||means[1]-means[0]<0.05)return 14;
for(auto resetPool:pools){OK(vkResetCommandPool(device,resetPool,0));A::InvalidatePool(resetPool,false);}
code=release(handle);printf("ngx_release=%08x\n",int(code));fflush(stdout);
 pass.reset();for(unsigned i=0;i<6;i++){vkDestroyImageView(device,views[i],nullptr);vkDestroyImage(device,images[i],nullptr);vkFreeMemory(device,memories[i],nullptr);}vkDestroyBuffer(device,buffer,nullptr);vkFreeMemory(device,bufferMemory,nullptr);vkDestroyFence(device,fence,nullptr);if(code!=1)return 11; }
 auto shutdown=(int(*)(VkDevice))GetProcAddress(nr,"NVSDK_NGX_VULKAN_Shutdown1");if(!shutdown)return 15;volatile int shut=shutdown(device);printf("ngx_shutdown=%08x\n",int(shut));if(shut!=1)return 16;FreeLibrary(nr);
for(unsigned slot=0;slot<4;slot++){vkDestroyFence(device,fences[slot],nullptr);vkDestroyCommandPool(device,pools[slot],nullptr);}unsigned retired=0;for(auto& s:A::completionSamples)if(s.reported)++retired;printf("tracking_samples=%zu retired=%u\n",A::completionSamples.size(),retired);if(retired<32)return 31;A::DestroyDevice(device);vkDestroyDevice(device,nullptr);vkDestroyInstance(instance,nullptr);
 return code==1?0:11;
}


