"""Generate shared host-layout rules. Emits hashes/metadata, not NVIDIA bytes."""
import argparse, hashlib, json, struct, base64
from pathlib import Path
def sha(b): return hashlib.sha256(b).hexdigest()
def pe(b):
    u16=lambda o:struct.unpack_from('<H',b,o)[0]
    u32=lambda o:struct.unpack_from('<I',b,o)[0]
    p=u32(60); o=p+24
    assert b[p:p+4]==b'PE\0\0' and u16(p+4)==0x8664 and u16(o)==0x20b
    sections=[]
    for i in range(u16(p+6)):
        s=o+u16(p+20)+i*40
        sections.append(dict(name=b[s:s+8].split(b'\0')[0].decode(),virtual_size=u32(s+8),rva=u32(s+12),size=u32(s+16),offset=u32(s+20),flags=u32(s+36)))
    return dict(entry=u32(o+16),image_base=struct.unpack_from('<Q',b,o+24)[0],image_size=u32(o+56),headers_size=u32(o+60),sections=sections,directories=[(u32(o+112+i*8),u32(o+116+i*8)) for i in range(16)])
def main():
    ap=argparse.ArgumentParser();ap.add_argument('--stock',required=True);ap.add_argument('--community',required=True);ap.add_argument('--patch',required=True);args=ap.parse_args()
    stock=Path(args.stock).read_bytes();community=Path(args.community).read_bytes()
    assert sha(stock)=='e16bcf15e16e13f527491cdf7845b2fe6521a738d8f7c9c721866a8496e1fc8e'
    assert sha(community)=='8270b350cd82de5ce89806872cdd6b6a9249b80836b91bbeb3573470744cc206'
    patch=json.loads(Path(args.patch).read_text(encoding='utf-8-sig'))
    def patched(data):
        out=bytearray(data)
        for h in patch['hunks']:
            off=h['offset'];r=base64.b64decode(h['replacement_base64'] if 'replacement_base64' in h else ''.join(h['replacement_base64_parts']))
            allowed=[base64.b64decode(h['expected_base64']),r]+[base64.b64decode(x) for x in h.get('compatible_input_base64',[])]
            assert any(data[off:off+len(x)]==x and (x or off==len(data)) for x in allowed)
            if off+len(r)>len(out):out.extend(bytes(off+len(r)-len(out)))
            out[off:off+len(r)]=r
        return bytes(out)
    profiles=[]
    for label,a,b in [('stock',stock,community),('d18',patched(stock),patched(community))]:
        layout=pe(a);assert pe(b)==layout
        regions=[]
        for sec in layout['sections']:
            if sec['name'] in ('.text','.rdata','.pdata','_RDATA','.reloc','.d16'):
                off,n=sec['offset'],sec['size']
                regions.append(dict(name=sec['name'],offset=off,size=n,hashes=list(dict.fromkeys([sha(a[off:off+n]),sha(b[off:off+n])]))))
            if sec['name']=='.data':
                # Keep initial state and complete backend/global-state tail, allow model data changes.
                for name,rva,n in [('data_prefix',sec['rva'],0x600),('backend_state',0x1141000,sec['rva']+sec['size']-0x1141000)]:
                    off=sec['offset']+rva-sec['rva'];assert a[off:off+n]==b[off:off+n]
                    regions.append(dict(name=name,offset=off,size=n,hashes=[sha(a[off:off+n])]))
        profiles.append(dict(name=label,layout=layout,regions=regions))
    root=Path(__file__).parent
    (root/'rules.json').write_text(json.dumps(dict(rule='d18-dx11-host-3108-v1',profiles=profiles),indent=2)+'\n',encoding='utf-8')
    out=['// Generated by generate.py. Hashes/layout metadata only.','#pragma once','namespace D18RuntimeGuard {','inline constexpr const char* Rule="d18-dx11-host-3108-v1";']
    for i,p in enumerate(profiles):
        out.append(f'inline constexpr Section Sections{i}[]={{')
        for s in p['layout']['sections']:out.append('{"%s",%su,%su,%su,%su,%su},'%(s['name'],s['rva'],s['virtual_size'],s['offset'],s['size'],s['flags']))
        out+=['};',f'inline constexpr Directory Directories{i}[]={{']
        out+=['{%su,%su},'%x for x in p['layout']['directories']];out+=['};',f'inline constexpr Region Regions{i}[]={{']
        for r in p['regions']:
            hs=r['hashes']+[None]*(2-len(r['hashes']))
            out.append('{"%s",%su,%su,{%s}},'%(r['name'],r['offset'],r['size'],','.join('"'+h+'"' if h else 'nullptr' for h in hs)))
        out.append('};')
    out.append('inline constexpr Profile Profiles[]={')
    for i,p in enumerate(profiles):
        l=p['layout'];out.append('{"%s",%su,%sull,%su,%su,Sections%d,sizeof(Sections%d)/sizeof(Section),Directories%d,Regions%d,sizeof(Regions%d)/sizeof(Region)},'%(p['name'],l['entry'],l['image_base'],l['image_size'],l['headers_size'],i,i,i,i,i))
    out+=['};','}'];(root/'rules.generated.h').write_text('\n'.join(out)+'\n',encoding='utf-8')
if __name__=='__main__':main()
