"""Generate a source-encoding-independent C++ dictionary and validate printf contracts."""
import argparse,json,re
from pathlib import Path
parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
locale=Path(__file__).resolve().parents[2]/'OptiScaler/menu'
source=locale/'D18Translations.zh-CN.json'
data=json.loads(source.read_text(encoding='utf-8-sig'))
pattern=r'%(?:[-+#0]*)(?:\d+|\*)?(?:\.(?:\d+|\*))?(?:hh|ll|[hljztL])?[diuoxXfFeEgGaAcsp%]'
def cpp(s):return '"'+''.join('\\x%02x'%b for b in s.encode('utf-8'))+'"'
for en,zh in data.items():
 assert re.findall(pattern,en)==re.findall(pattern,zh),(en,'printf contract changed')
 assert '###' not in zh and '\0' not in zh
lines=['// Generated by tools/D24/generate-ui-translations.py. Edit the JSON source.','#pragma once','namespace D18Ui {','struct Translation { const char* en; const char* zh; };','inline constexpr Translation translations[] = {']
lines += [' {'+cpp(en)+','+cpp(zh)+'},' for en,zh in data.items()]
lines += ['};','}']
text='\n'.join(lines)+'\n';target=locale/'D18Translations.h'
if args.check:assert target.read_text(encoding='ascii')==text,'Generated dictionary is stale'
else:target.write_text(text,encoding='ascii')
print('Translations:',len(data),'| printf contracts: PASS')
